<a href="https://colab.research.google.com/github/2403a52239-netizen/NLP/blob/main/lab_6_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

LDA with Sample Data and BoW

In [ ]:
import pandas as pd
data=pd.read_excel('/content/LDA-Data (1).xlsx')
display(data.head())

                             News
0   Virat scored century in match
1            BJP won in elections
2  Bumra took 5 wicket in a match
3  Congress form state government

In [ ]:
import re
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')

def nltk_preprocessing_pipeline(text):

    lemmatizer = WordNetLemmatizer()
    stop_words = set(stopwords.words('english'))

    text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)
    text = re.sub(r'<.*?>', '', text)
    text = re.sub(r'@\w+', '', text)
    text = re.sub(r'#\w+', '', text)

    text = text.lower()
    emoji_pattern = re.compile(
        "["
        "\U0001F600-\U0001F64F"
        "\U0001F300-\U0001F5FF"
        "\U0001F680-\U0001F6FF"
        "\U0001F1E0-\U0001F1FF"
        "\U00002702-\U000027B0"
        "\U000024C2-\U0001F251"
        "]+", flags=re.UNICODE
    )
    text = emoji_pattern.sub(r'', text)

    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()


    tokenized_words = word_tokenize(text)


    filtered_words = [word for word in tokenized_words if word not in stop_words]


    lemmatized_words = [lemmatizer.lemmatize(word) for word in filtered_words]


    clean_summary = ' '.join(lemmatized_words)

    return clean_summary

print("NLTK preprocessing pipeline function created successfully!")

NLTK preprocessing pipeline function created successfully!

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [ ]:
data['clean_News'] = data['News'].apply(nltk_preprocessing_pipeline)
print("\nComparison of previous clean_summaries and new clean_summaries_pipeline (first 5 rows):")
print(data[['clean_News']].head())

Comparison of previous clean_summaries and new clean_summaries_pipeline (first 5 rows):
                       clean_News
0      virat scored century match
1                    bjp election
2       bumra took 5 wicket match
3  congress form state government

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

count_vectorizer = CountVectorizer(max_df=0.95, min_df=1, stop_words='english')
doc_term_matrix = count_vectorizer.fit_transform(data['clean_News'])

In [ ]:
import pandas as pd

feature_names = count_vectorizer.get_feature_names_out()

bow_df = pd.DataFrame(doc_term_matrix.toarray(),columns=feature_names)

bow_top_10 = bow_df.head(10)
print(bow_top_10)

   bjp  bumra  century  congress  election  form  government  match  scored  \
0    0      0        1         0         0     0           0      1       1
1    1      0        0         0         1     0           0      0       0
2    0      1        0         0         0     0           0      1       0
3    0      0        0         1         0     1           1      0       0

   state  took  virat  wicket
0      0     0      1       0
1      0     0      0       0
2      0     1      0       1
3      1     0      0       0

In [ ]:
from sklearn.decomposition import LatentDirichletAllocation


num_topics = 2
LDA = LatentDirichletAllocation(n_components=num_topics, random_state=42)
LDA.fit(doc_term_matrix)

LatentDirichletAllocation(n_components=2, random_state=42)

In [ ]:
def display_topics(model, feature_names, num_top_words):
    for topic_idx in range(len(model.components_)):
        print(f"\nTopic {topic_idx}:")

        topic_weights = model.components_[topic_idx]


        sorted_indices = topic_weights.argsort()[::-1]


        top_indices = sorted_indices[:num_top_words]


        for idx in top_indices:
            print(feature_names[idx], end=" ")
        print()

In [ ]:
num_top_words = 10
print(f"\nTop {num_top_words} words per topic:")
display_topics(LDA, count_vectorizer.get_feature_names_out(), num_top_words)

Top 10 words per topic:

Topic 0:
form government congress state election bjp match wicket bumra took

Topic 1:
match virat century scored took bumra wicket bjp election state

In [ ]:
num_top_words = 10
print(f"\nTop {num_top_words} words per topic:")
display_topics(LDA, count_vectorizer.get_feature_names_out(), num_top_words)

DataFrame with assigned topics (first 5 rows):
                       clean_News  topic
0      virat scored century match      1
1                    bjp election      0
2       bumra took 5 wicket match      1
3  congress form state government      0

LDA with Kaggle Data and BoW

In [ ]:
import pandas as pd
df=pd.read_csv("/content/arxiv_data.csv", on_bad_lines='skip', engine='python')

In [ ]:
df.head()

,titles,summaries,terms
0,Survey on Semantic Stereo Matching / Semantic ...,Stereo matching is one of the widely used tech...,"['cs.CV', 'cs.LG']"
1,FUTURE-AI: Guiding Principles and Consensus Re...,The recent advancements in artificial intellig...,"['cs.CV', 'cs.AI', 'cs.LG']"
2,Enforcing Mutual Consistency of Hard Regions f...,"In this paper, we proposed a novel mutual cons...","['cs.CV', 'cs.AI']"
3,Parameter Decoupling Strategy for Semi-supervi...,Consistency training has proven to be an advan...,['cs.CV']
4,Background-Foreground Segmentation for Interio...,"To ensure safety in automated driving, the cor...","['cs.CV', 'cs.LG']"

In [ ]:
import re
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')

def nltk_preprocessing_pipeline(text):
    lemmatizer = WordNetLemmatizer()
    stop_words = set(stopwords.words('english'))


    text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)
    text = re.sub(r'<.*?>', '', text)
    text = re.sub(r'@\w+', '', text)
    text = re.sub(r'#\w+', '', text)

    text = text.lower()

    emoji_pattern = re.compile(
        "["
        "\U0001F600-\U0001F64F"
        "\U0001F300-\U0001F5FF"
        "\U0001F680-\U0001F6FF"
        "\U0001F1E0-\U0001F1FF"
        "\U00002702-\U000027B0"
        "\U000024C2-\U0001F251"
        "]+", flags=re.UNICODE
    )
    text = emoji_pattern.sub(r'', text)

    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()

    tokenized_words = word_tokenize(text)

    filtered_words = [word for word in tokenized_words if word not in stop_words]

    lemmatized_words = [lemmatizer.lemmatize(word) for word in filtered_words]

    clean_summary = ' '.join(lemmatized_words)

    return clean_summary

print("NLTK preprocessing pipeline function created successfully!")

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

NLTK preprocessing pipeline function created successfully!

In [ ]:
df['clean_summaries_pipeline'] = df['summaries'].apply(nltk_preprocessing_pipeline)
print("\nComparison of previous clean_summaries and new clean_summaries_pipeline (first 5 rows):")
print(df[['clean_summaries_pipeline']].head())

Comparison of previous clean_summaries and new clean_summaries_pipeline (first 5 rows):
                            clean_summaries_pipeline
0  stereo matching one widely used technique infe...
1  recent advancement artificial intelligence ai ...
2  paper proposed novel mutual consistency networ...
3  consistency training proven advanced semisuper...
4  ensure safety automated driving correct percep...

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

count_vectorizer = CountVectorizer(max_df=0.95, min_df=2, stop_words='english')
doc_term_matrix = count_vectorizer.fit_transform(df['clean_summaries_pipeline'])

In [ ]:
import pandas as pd

feature_names = count_vectorizer.get_feature_names_out()

bow_df = pd.DataFrame(doc_term_matrix.toarray(),columns=feature_names)

bow_top_10 = bow_df.head(10)
print(bow_top_10)

   00  000  00001  00002  00005  0001  00010  0002  0003  0004  ...  zslkg  \
0   0    0      0      0      0     0      0     0     0     0  ...      0
1   0    0      0      0      0     0      0     0     0     0  ...      0
2   0    0      0      0      0     0      0     0     0     0  ...      0
3   0    0      0      0      0     0      0     0     0     0  ...      0
4   0    0      0      0      0     0      0     0     0     0  ...      0
5   0    0      0      0      0     0      0     0     0     0  ...      0
6   0    0      0      0      0     0      0     0     0     0  ...      0
7   0    0      0      0      0     0      0     0     0     0  ...      0
8   0    0      0      0      0     0      0     0     0     0  ...      0
9   0    0      0      0      0     0      0     0     0     0  ...      0

   zspu  zssbir  zsslr  zssr  zurich  zvos  zynq  zynq7000  zynqnet
0     0       0      0     0       0     0     0         0        0
1     0       0      0     0       0     0     0         0        0
2     0       0      0     0       0     0     0         0        0
3     0       0      0     0       0     0     0         0        0
4     0       0      0     0       0     0     0         0        0
5     0       0      0     0       0     0     0         0        0
6     0       0      0     0       0     0     0         0        0
7     0       0      0     0       0     0     0         0        0
8     0       0      0     0       0     0     0         0        0
9     0       0      0     0       0     0     0         0        0

[10 rows x 47626 columns]

In [ ]:
from sklearn.decomposition import LatentDirichletAllocation


num_topics = 2
LDA = LatentDirichletAllocation(n_components=num_topics, random_state=42)
LDA.fit(doc_term_matrix)

LatentDirichletAllocation(n_components=2, random_state=42)

In [ ]:
def display_topics(model, feature_names, num_top_words):
    for topic_idx in range(len(model.components_)):
        print(f"\nTopic {topic_idx}:")


        topic_weights = model.components_[topic_idx]


        sorted_indices = topic_weights.argsort()[::-1]


        top_indices = sorted_indices[:num_top_words]

        for idx in top_indices:
            print(feature_names[idx], end=" ")
        print()

In [ ]:
num_top_words = 10
print(f"\nTop {num_top_words} words per topic:")
display_topics(LDA, count_vectorizer.get_feature_names_out(), num_top_words)

Top 10 words per topic:

Topic 0:
image method network object model feature detection segmentation proposed propose

Topic 1:
learning model data method network graph algorithm task approach problem

In [ ]:
document_topics = LDA.transform(doc_term_matrix)
df['topic'] = document_topics.argmax(axis=1)

print("\nDataFrame with assigned topics (first 5 rows):")
print(df[['clean_summaries_pipeline', 'topic']].head())

DataFrame with assigned topics (first 5 rows):
                            clean_summaries_pipeline  topic
0  stereo matching one widely used technique infe...      0
1  recent advancement artificial intelligence ai ...      1
2  paper proposed novel mutual consistency networ...      0
3  consistency training proven advanced semisuper...      0
4  ensure safety automated driving correct percep...      0

In [ ]:
from sklearn.decomposition import NMF


num_topics = 2
nmf_model = NMF(n_components=num_topics, random_state=42)


nmf_model.fit(doc_term_matrix)
print("NMF model initialized and fitted successfully.")

NMF model initialized and fitted successfully.

In [ ]:
num_top_words = 10
print(f"\nTop {num_top_words} words per topic (NMF):")
display_topics(nmf_model, count_vectorizer.get_feature_names_out(), num_top_words)

Top 10 words per topic (NMF):

Topic 0:
model learning data network method graph task approach representation feature

Topic 1:
image method object network segmentation feature detection proposed result propose

In [ ]:
document_topics = nmf_model.transform(doc_term_matrix)
df['topic'] = document_topics.argmax(axis=1)

print("\nDataFrame with assigned topics (first 5 rows):")
print(df[['clean_summaries_pipeline', 'topic']].head())

DataFrame with assigned topics (first 5 rows):
                            clean_summaries_pipeline  topic
0  stereo matching one widely used technique infe...      1
1  recent advancement artificial intelligence ai ...      1
2  paper proposed novel mutual consistency networ...      0
3  consistency training proven advanced semisuper...      0
4  ensure safety automated driving correct percep...      0

NMF with sample data and BoW

In [ ]:
from sklearn.decomposition import NMF

num_topics = 2
nmf_model = NMF(n_components=num_topics, random_state=42)

nmf_model.fit(doc_term_matrix)
print("NMF model initialized and fitted successfully.")

NMF model initialized and fitted successfully.

In [33]:
print(f"\nTop {num_top_words} words per topic (NMF):")
display_topics(nmf_model, count_vectorizer.get_feature_names_out(), num_top_words)

Top 10 words per topic (NMF):

Topic 0:
match virat took scored wicket bumra century bjp election state

Topic 1:
state form congress government election bjp took virat wicket scored

In [34]:
document_topics = nmf_model.transform(doc_term_matrix)
data['topic'] = document_topics.argmax(axis=1)

print("\nDataFrame with assigned topics (first 5 rows):")
print(data[['clean_News', 'topic']].head())

DataFrame with assigned topics (first 5 rows):
                       clean_News  topic
0      virat scored century match      0
1                    bjp election      1
2       bumra took 5 wicket match      0
3  congress form state government      1

 NMF with Kaggle Data and BoW

In [40]:
import pandas as pd
df = pd.read_csv('arxiv_data.csv', engine='python', nrows=1000)
df.head()

,titles,summaries,terms
0,Survey on Semantic Stereo Matching / Semantic ...,Stereo matching is one of the widely used tech...,"['cs.CV', 'cs.LG']"
1,FUTURE-AI: Guiding Principles and Consensus Re...,The recent advancements in artificial intellig...,"['cs.CV', 'cs.AI', 'cs.LG']"
2,Enforcing Mutual Consistency of Hard Regions f...,"In this paper, we proposed a novel mutual cons...","['cs.CV', 'cs.AI']"
3,Parameter Decoupling Strategy for Semi-supervi...,Consistency training has proven to be an advan...,['cs.CV']
4,Background-Foreground Segmentation for Interio...,"To ensure safety in automated driving, the cor...","['cs.CV', 'cs.LG']"

In [43]:
import re
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')
def nltk_preprocessing_pipeline(text):
    lemmatizer = WordNetLemmatizer()
    stop_words = set(stopwords.words('english'))
    text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)
    text = re.sub(r'<.*?>', '', text)
    text = re.sub(r'@\w+', '', text)
    text = re.sub(r'#\w+', '', text)
    text = text.lower()
    emoji_pattern = re.compile(
        "["
        "\U0001F600-\U0001F64F"
        "\U0001F300-\U0001F5FF"
        "\U0001F680-\U0001F6FF"
        "\U0001F1E0-\U0001F1FF"
        "\U00002702-\U000027B0"
        "\U000024C2-\U0001F251"
        "]+", flags=re.UNICODE
    )
    text = emoji_pattern.sub(r'', text)
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    tokenized_words = word_tokenize(text)
    filtered_words = [word for word in tokenized_words if word not in stop_words]
    lemmatized_words = [lemmatizer.lemmatize(word) for word in filtered_words]
    clean_summary = ' '.join(lemmatized_words)
    return clean_summary
print("NLTK preprocessing pipeline function created successfully!")

NLTK preprocessing pipeline function created successfully!

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [45]:
df['clean_summaries_pipeline'] = df['summaries'].apply(nltk_preprocessing_pipeline)

count_vectorizer = CountVectorizer(max_df=0.95, min_df=2, stop_words='english')
doc_term_matrix = count_vectorizer.fit_transform(df['clean_summaries_pipeline'])

print("Kaggle data preprocessing and vectorization complete for NMF.")

Kaggle data preprocessing and vectorization complete for NMF.

In [35]:
from sklearn.decomposition import NMF
num_topics = 2
nmf_model = NMF(n_components=num_topics, random_state=42)
nmf_model.fit(doc_term_matrix)
print("NMF model initialized and fitted successfully.")

NMF model initialized and fitted successfully.

In [38]:
num_top_words = 10
print(f"\nTop {num_top_words} words per topic (NMF):")
display_topics(nmf_model, count_vectorizer.get_feature_names_out(), num_top_words)

Top 10 words per topic (NMF):

Topic 0:
match virat took scored wicket bumra century bjp election state

Topic 1:
state form congress government election bjp took virat wicket scored

In [47]:
from sklearn.decomposition import NMF
doc_term_matrix
num_topics = 2
nmf_model = NMF(n_components=num_topics, random_state=42)
nmf_model.fit(doc_term_matrix)

document_topics = nmf_model.transform(doc_term_matrix)
df['topic'] = document_topics.argmax(axis=1)

print("\n 5 first rows in DataFrame with assigned topics:")
print(df[['clean_summaries_pipeline', 'topic']].head())

 5 first rows in DataFrame with assigned topics:
                            clean_summaries_pipeline  topic
0  stereo matching one widely used technique infe...      1
1  recent advancement artificial intelligence ai ...      0
2  paper proposed novel mutual consistency networ...      0
3  consistency training proven advanced semisuper...      0
4  ensure safety automated driving correct percep...      0

 NMF with Sample Data and TFIDF

In [49]:
import pandas as pd
data=pd.read_excel('/content/LDA-Data (1).xlsx')
data.head()

                             News
0   Virat scored century in match
1            BJP won in elections
2  Bumra took 5 wicket in a match
3  Congress form state government

In [50]:
import nltk
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt_tab')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [51]:
data['clean_News'] = data['News'].apply(nltk_preprocessing_pipeline)
print("Comparison of original 'News' and new 'clean_News' (first 5 rows):")
print(data[['News', 'clean_News']].head())

Comparison of original 'News' and new 'clean_News' (first 5 rows):
                             News                      clean_News
0   Virat scored century in match      virat scored century match
1            BJP won in elections                    bjp election
2  Bumra took 5 wicket in a match       bumra took 5 wicket match
3  Congress form state government  congress form state government

In [52]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer(max_df=0.95, min_df=1, stop_words='english')
tfidf_matrix = tfidf_vectorizer.fit_transform(data['clean_News'])

print("TFIDF vectorization complete. The shape of the TFIDF matrix is:", tfidf_matrix.shape)

TFIDF vectorization complete. The shape of the TFIDF matrix is: (4, 13)

In [53]:
from sklearn.decomposition import NMF

num_topics = 2
nmf_model_tfidf = NMF(n_components=num_topics, random_state=42)
nmf_model_tfidf.fit(tfidf_matrix)

print("NMF model for TFIDF matrix initialized and fitted successfully.")

NMF model for TFIDF matrix initialized and fitted successfully.

In [54]:
num_top_words = 10
print(f"\nTop {num_top_words} words per topic (NMF with TFIDF):")
display_topics(nmf_model_tfidf, tfidf_vectorizer.get_feature_names_out(), num_top_words)

Top 10 words per topic (NMF with TFIDF):

Topic 0:
match bumra wicket took virat scored century state government election

Topic 1:
election bjp form government state congress took virat wicket scored

In [55]:
document_topics = nmf_model_tfidf.transform(tfidf_matrix)
data['topic'] = document_topics.argmax(axis=1)

print("\nDataFrame with assigned topics (first 5 rows):")
print(data[['clean_News', 'topic']].head())

DataFrame with assigned topics (first 5 rows):
                       clean_News  topic
0      virat scored century match      0
1                    bjp election      1
2       bumra took 5 wicket match      0
3  congress form state government      1

NMF with Kaggle Data and TFIDF

In [57]:
df = pd.read_csv('arxiv_data.csv', engine='python', nrows=1000)
df.head()

,titles,summaries,terms
0,Survey on Semantic Stereo Matching / Semantic ...,Stereo matching is one of the widely used tech...,"['cs.CV', 'cs.LG']"
1,FUTURE-AI: Guiding Principles and Consensus Re...,The recent advancements in artificial intellig...,"['cs.CV', 'cs.AI', 'cs.LG']"
2,Enforcing Mutual Consistency of Hard Regions f...,"In this paper, we proposed a novel mutual cons...","['cs.CV', 'cs.AI']"
3,Parameter Decoupling Strategy for Semi-supervi...,Consistency training has proven to be an advan...,['cs.CV']
4,Background-Foreground Segmentation for Interio...,"To ensure safety in automated driving, the cor...","['cs.CV', 'cs.LG']"

In [58]:
df['clean_summaries_pipeline'] = df['summaries'].apply(nltk_preprocessing_pipeline)
print("Comparison of original 'summaries' and new 'clean_summaries_pipeline' (first 5 rows):")
print(df[['summaries', 'clean_summaries_pipeline']].head())

Comparison of original 'summaries' and new 'clean_summaries_pipeline' (first 5 rows):
                                           summaries  \
0  Stereo matching is one of the widely used tech...
1  The recent advancements in artificial intellig...
2  In this paper, we proposed a novel mutual cons...
3  Consistency training has proven to be an advan...
4  To ensure safety in automated driving, the cor...

                            clean_summaries_pipeline
0  stereo matching one widely used technique infe...
1  recent advancement artificial intelligence ai ...
2  paper proposed novel mutual consistency networ...
3  consistency training proven advanced semisuper...
4  ensure safety automated driving correct percep...

In [59]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer(max_df=0.95, min_df=2, stop_words='english')
tfidf_matrix = tfidf_vectorizer.fit_transform(df['clean_summaries_pipeline'])

print("TFIDF vectorization complete. The shape of the TFIDF matrix is:", tfidf_matrix.shape)

TFIDF vectorization complete. The shape of the TFIDF matrix is: (1000, 4386)

In [60]:
from sklearn.decomposition import NMF

num_topics = 2
nmf_model_tfidf = NMF(n_components=num_topics, random_state=42)
nmf_model_tfidf.fit(tfidf_matrix)

print("NMF model for TFIDF matrix initialized and fitted successfully.")

NMF model for TFIDF matrix initialized and fitted successfully.

In [61]:
num_top_words = 10
print(f"\nTop {num_top_words} words per topic (NMF with TFIDF):")
display_topics(nmf_model_tfidf, tfidf_vectorizer.get_feature_names_out(), num_top_words)

Top 10 words per topic (NMF with TFIDF):

Topic 0:
network method feature architecture model object proposed result approach 3d

Topic 1:
domain data learning annotation training model label medical method labeled

In [62]:
document_topics = nmf_model_tfidf.transform(tfidf_matrix)
df['topic'] = document_topics.argmax(axis=1)

print("\nDataFrame with assigned topics (first 5 rows):")
print(df[['clean_summaries_pipeline', 'topic']].head())

DataFrame with assigned topics (first 5 rows):
                            clean_summaries_pipeline  topic
0  stereo matching one widely used technique infe...      0
1  recent advancement artificial intelligence ai ...      1
2  paper proposed novel mutual consistency networ...      1
3  consistency training proven advanced semisuper...      1
4  ensure safety automated driving correct percep...      0